# Generated by Django 3.1.1 on 2020-12-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Supplied_list',
        ),
    ]
