# Generated by Django 3.1.1 on 2020-12-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_requiredlist_supplier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requiredlist',
            old_name='supplier_id',
            new_name='supplier_name',
        ),
    ]
