# Generated by Django 3.1.1 on 2020-12-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20201205_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplied_list',
            old_name='name',
            new_name='Supplier_name',
        ),
    ]
