# Generated by Django 3.1.3 on 2020-11-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='prodcut_id',
            new_name='product_id',
        ),
    ]
